"""empty message

Revision ID: 5ce34336e6ed
Revises: c2118a66ddb6
Create Date: 2024-12-29 21:43:05.677960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce34336e6ed'
down_revision = 'c2118a66ddb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
